export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  ownerPrivyDid: process.env.OWNER_PRIVY_DID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  seraApiBaseUrl: (process.env.SERA_API_BASE_URL ?? "https://api.sera.cx/api/v1").replace(/\/+$/, ""),
  seraApiKey: process.env.SERA_API_KEY ?? "",
  seraApiSecret: process.env.SERA_API_SECRET ?? "",
  seraCredentialEncryptionKey: process.env.SERA_CREDENTIAL_ENCRYPTION_KEY ?? "",
};
